---
name: Unit Tests

on:
    workflow_call:
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
        inputs:
            # Ubuntu 20.04 runner no more supported (see https://github.com/actions/runner-images/issues/11101)
            operating-system:
                description: "OS name and version runtime"
                required: false
                default: "ubuntu-22.04"
                type: string
            composer-options:
                description: "Composer options for ramsey/composer-install GitHub Action"
                required: false
                default: "--prefer-dist --no-scripts"
                type: string

permissions:
    contents: read

jobs:
    unit_tests:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        os: ${{ inputs.operating-system }}
                        php: 8.1
                        extensions: amqp,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,json,ldap,libxml,lzf,mbstring,memcache,memcached,mongodb,msgpack,mysqli,oauth,oci8,opcache,openssl,opentelemetry,pcntl,pcre,pdo,pgsql,phar,posix,raphf,pecl_http,readline,redis,reflection,session,shmop,simplexml,sockets,solr,spl,sqlite3,ssh2-beta,standard,sysvmsg,sysvsem,sysvshm,tokenizer,uuid,xdebug,xhprof,xml,xmldiff,xmlreader,xmlwriter,xpass,xsl,yac,zip,zlib
                        tools: phpunit:10.5
                    -
                        os: ${{ inputs.operating-system }}
                        php: 8.2
                        extensions: amqp,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,json,ldap,libxml,lzf,mbstring,memcache,memcached,mongodb,msgpack,mysqli,oauth,oci8,opcache,openssl,opentelemetry,pcntl,pcre,pdo,pgsql,phar,posix,random,raphf,pecl_http,readline,redis,reflection,session,shmop,simplexml,sockets,solr,spl,sqlite3,ssh2-beta,standard,sysvmsg,sysvsem,sysvshm,tokenizer,uuid,xdebug,xhprof,xml,xmldiff,xmlreader,xmlwriter,xpass,xsl,yac,zip,zlib
                        tools: phpunit:11.5
                    -
                        os: ${{ inputs.operating-system }}
                        php: 8.3
                        extensions: amqp,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,json,ldap,libxml,lzf,mbstring,memcache,memcached,mongodb,msgpack,mysqli,oauth,oci8,opcache,openssl,pcntl,pcre,pdo,pgsql,phar,posix,random,raphf,pecl_http,readline,redis,reflection,session,shmop,simplexml,sockets,solr,spl,sqlite3,ssh2-beta,standard,sysvmsg,sysvsem,sysvshm,tokenizer,uuid,xdebug,xhprof,xml,xmldiff,xmlreader,xmlwriter,xpass,xsl,yac,zip,zlib
                        tools: phpunit:12.4
                    -
                        os: ubuntu-22.04
                        php: 8.4
                        extensions: amqp,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,json,ldap,libxml,lzf,mbstring,memcache,memcached,mongodb,msgpack,mysqli,oauth,oci8,opcache,openssl,pcntl,pcre,pdo,pgsql,phar,posix,random,raphf,pecl_http,readline,redis,reflection,session,shmop,simplexml,sockets,solr,spl,sqlite3,ssh2-beta,standard,sysvmsg,sysvsem,sysvshm,tokenizer,uuid,xdebug,xhprof,xml,xmldiff,xmlreader,xmlwriter,xpass,xsl,yac,zip,zlib
                        tools: phpunit:12.4
                    -
                        os: ubuntu-22.04
                        php: 8.5
                        extensions: apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gettext,gmp,hash,iconv,imap,intl,json,ldap,libxml,lzf,mbstring,mongodb,msgpack,mysqli,opcache,openssl,pcntl,pcre,pdo,pgsql,phar,posix,random,raphf,pecl_http,readline,redis,reflection,session,shmop,simplexml,sockets,spl,sqlite3,ssh2-beta,standard,sysvmsg,sysvsem,sysvshm,tokenizer,uuid,xhprof,xml,xmldiff,xmlreader,xmlwriter,xpass,xsl,yac,zip,zlib
                        tools: phpunit:12.4

        env:
            APP_ENV: dev  # see explains at https://github.com/llaville/php-compatinfo-db/issues/101
            DATABASE_URL: "sqlite:///%kernel.cache_dir%/compatinfo-db.sqlite"

        steps:
            -   # https://github.com/actions/checkout
                name: Checkout
                uses: actions/checkout@v6.0.1
                with:
                    # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
                    persist-credentials: false

            -
                name: Setup Libraries
                run: |
                    sudo apt-get update
                    sudo apt-fast install libcurl4-openssl-dev -y
                    sudo apt-fast install libssh2-1-dev -y
                    sudo apt-fast install librdkafka-dev -y

            -   # https://github.com/shivammathur/cache-extensions
                name: Setup cache environment
                id: extcache
                uses: shivammathur/cache-extensions@1.13.0
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ matrix.extensions }}
                    key: cache-v6

            -   # https://github.com/actions/cache
                name: Cache extensions
                uses: actions/cache@v5.0.1
                with:
                    path: ${{ steps.extcache.outputs.dir }}
                    key: ${{ steps.extcache.outputs.key }}
                    restore-keys: ${{ steps.extcache.outputs.key }}

            -   # https://github.com/shivammathur/setup-php
                name: Setup PHP runtime
                uses: shivammathur/setup-php@2.36.0
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ matrix.extensions }}
                    tools: ${{ matrix.tools }}

            -   # https://github.com/ramsey/composer-install
                name: Install Composer dependencies
                uses: ramsey/composer-install@3.1.1
                with:
                    dependency-versions: "highest"
                    composer-options: ${{ inputs.composer-options }}

            -   # https://github.com/llaville/php-compatinfo-db
                name: Build Database
                run: |
                    bin/compatinfo-db db:new --ansi

            -   # https://github.com/llaville/php-compatinfo-db
                name: Check Database
                run: |
                    bin/compatinfo-db diagnose --ansi
                    bin/compatinfo-db db:list --installed --ansi

            -   # https://github.com/sebastianbergmann/phpunit
                name: Unit tests with PHPUnit
                run: phpunit --group reference --do-not-cache-result --no-progress --do-not-fail-on-phpunit-warning --do-not-fail-on-phpunit-deprecation
